### PR TITLE
Allow subscriber public keys on NIST curve P-521

### PR DESCRIPTION
**Pull request by aarongable**
Fixes https://github.com/letsencrypt/cp-cps/issues/218

### CODE REVIEW

**Comment by pgporada** [comment]
Related to https://github.com/letsencrypt/boulder/pull/7541#issuecomment-2163178922 and  https://github.com/letsencrypt/boulder/pull/7543

**Comment by hablutzel1** [comment]
I haven't got into the details, but https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#51-algorithms isn't going to be a problem?

> The following curves are not prohibited, but are not currently supported: P-521, Curve25519, and Curve448.

**Comment by aarongable** [comment]
> I haven't got into the details, but https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#51-algorithms isn't going to be a problem?

Correct, that's not a problem. As that says, P-521 is not prohibited, so it's not a policy issue for us to allow it, just an interoperability issue. And as the linked issue says, the purpose of this change is just to ensure that we are not limiting ourselves in ways that are not required.

**Comment by hablutzel1** [comment]
But won't this cause interoperability problems for the LE subscribers unknowingly using P-521 keys?

**Comment by aarongable** [comment]
This is a policy document only; changes to actual code are separate. Changing this policy _allows_ us to make those code changes, but does not require us to do so.

**Comment by aarongable** [comment]
Superseded by https://github.com/letsencrypt/cp-cps/pull/228

**Pull request closed without merging**
