### PR TITLE
Update Audit Log Retention period

### PR DESCRIPTION
**Pull request by andygabby**
Update Audit Log Retention time to match the BR 5.4.3 requirement
of two years.

### CODE REVIEW

**Review by aarongable — APPROVED** [review]
The discrepancy with Section 5.5.2 is so unfortunate but I think that's being fixed in the BRs soon too.

**Comment by bdaehlie** [comment]
Let's hold off on this until the BR fix is complete.

**Comment by jkarner** [comment]
Ballot SC51: Reduce and Clarify Audit Log and Records Archival Retention Requirements is currently in the review period and will likely be voted on soon. If it passes, we can move forward with the PR.

**Comment by aarongable** [comment]
Ended up creating a new PR instead of just updating this one, oops: https://github.com/letsencrypt/cp-cps/pull/171

**Pull request closed without merging**
